#################################################################################################################
#
# IMPORTANT: This docker configuration must be use only for local execution and test purposes. PLEASE NOT APPLY THIS
# DOCKER DEPLOYMENT IN ANY CLOUD SERVER.
#
#################################################################################################################


version: '3.0'

services:
##################################################################################################################
############################################ Database container ##################################################
  db:
    image: mysql:5.7
    container_name: ppk-transactions-mysql
    command: --default-authentication-plugin=mysql_native_password
# If you have some data and structure already built, then you can add to mysql data volume, if not then keep this
# configuration.
    volumes:
    - ${PWD}/data/mysql:/var/lib/mysql
    restart: always
# Update DB environment variables with your own values
    environment:
      MYSQL_ROOT_PASSWORD: ppkpassword
      MYSQL_DATABASE: ppk_transactions
      MYSQL_USER: ppkuser
      MYSQL_PASSWORD: ppkpassword
# You must be sure that each application is dispatched by a different port to avoid service crash
    ports:
    - 3361:3306

##################################################################################################################
############################################ Application container ################################################
  ppk-transaction-be-api:
    image: tomcat:8
# Update container name with your own project proper container name (project-service-type)
    container_name: ppk-transaction-be-api
# Update this volume link with your own .war generated file
    volumes:
      - ${PWD}/target/pappking.transaction.be.api.war:/usr/local/tomcat/webapps/api.war
    restart: always
# Database must be linked to the project to be sure that they are in the same docker network
    links:
      - db
    depends_on:
      - db
# You should create your own env variables to setup your app
    environment:
      USERS_DB_URL: jdbc:mysql://db:3361/ppk_transactions
      USERS_JDBC_USERNAME: ppkuser
      USERS_JDBC_PASSWORD: ppkpassword
# You must be sure that each application is dispatched by a different port to avoid service crash
    ports:
      - 6001:8080
volumes:
  db_data: